name: Exercise17 - build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: sudo apt-get install build-essential
      - name: Build the main program
        run: make run EXPR='2*(3+4)'
      - name: Run the expression test
        run: make test_expr
      - name: Run the stack test
        run: make test_stack
      - name: Upload the programs and tests
        uses: actions/upload-artifact@v2.2.3
        with:
          name: program & tests
          path: |
            build/main.exe
            build/test_stack.exe
            build/expression_test.exe
