name: Exercise17 - release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential
      - name: Build
        run: |
          make run EXPR='2*(3+4)'
          make test_expr
          make test_stack
          cd build
          zip program.zip main.exe test_expr.exe test_stack.exe
      - name: Run the expression test
        run: make test_expr
      - name: Run the stack test
        run: make test_stack
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Version
          files: build/program.zip
